services:
  db:
    ports:
      - "${HOST_BIND_IP}:5432:5432"
    environment:
      - DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_TEST_DB_NAME}
      - POSTGRES_DB=${POSTGRES_TEST_DB_NAME}

  api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${TEST_PORT}:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_TEST_DB_NAME}
      - POSTGRES_DB_NAME=${POSTGRES_TEST_DB_NAME}
