services:
  db:
    environment:
      - DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DEV_DB_NAME}
      - POSTGRES_DB=${POSTGRES_DEV_DB_NAME}

  api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${DEV_PORT}:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DEV_DB_NAME}
      - POSTGRES_DB_NAME=${POSTGRES_DEV_DB_NAME}
    volumes:
      - .:/app
      - /app/.venv
