services:
  api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${DEV_PORT}:8000"
    volumes:
      - .:/app
      - /app/.venv

  admin:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${ADMIN_DEV_PORT}:8010"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - EXTERNAL_API_URL=http://${HOST_BIND_IP}:${DEV_PORT}

