services:
  api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${TEST_PORT}:8000"
    volumes:
      - "./src:/app/src"

  admin:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${ADMIN_TEST_PORT}:8010"
    volumes:
      - "./src:/app/src"
    environment:
      - OBS_API_URL=http://api:8000

