services:
  api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${DEV_PORT}:8000"
    volumes:
      - .:/app
      - /app/.venv
      - chroma-db-dev:/app/chroma_db
      - obsidian-vault-dev:/app/obsidian-vault

volumes:
  chroma-db-dev:
    driver: local
    name: ${PROJECT_NAME}-chroma-db-dev
    external: false
  obsidian-vault-dev:
    driver: local
    name: ${PROJECT_NAME}-obsidian-vault-dev
    external: false
